language: julia

os:
  - linux

julia:
  - 1.2
  - 1.3

notifications:
  email:
    recipients: joaoluisok@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

jobs:
  include:
    - stage: Documentation
      julia: 1.3
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs -e 'println("Please create docs")'
      after_success: skip

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("DLLFBSG")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
